# 1. What is the total revenue generated by each restaurant?
# Business Value: Identifies top-performing partners and helps in ranking restaurants by financial contribution.


# SELECT restaurant_name, SUM(order_value) AS total_revenue
# FROM orders
# GROUP BY restaurant_name
# ORDER BY total_revenue DESC;

# SELECT payment_method, COUNT(order_id) AS order_count
# FROM orders
# GROUP BY payment_method
# ORDER BY order_count DESC;

# SELECT COUNT(order_id) AS discounted_orders, ROUND(AVG(order_value),2) AS avg_discounted_value
# FROM orders
# WHERE discount_used = 'Yes'; -- Assuming 'Yes'/'No' or specific codes

# SELECT order_date, COUNT(order_id) AS daily_order_count
# FROM orders
# GROUP BY order_date
# ORDER BY order_date LIMIT 30;

# SELECT restaurant_name, ROUND(AVG(order_value),2) AS aov
# FROM orders
# GROUP BY restaurant_name
# HAVING aov > 50;






import streamlit as st
import pandas as pd
import sqlite3

# 1. Configuration & Styling
st.set_page_config(page_title="Orders Q&A", layout="wide")

# 2. Database Connection Helper
def run_query(query):
    # Replace 'business_data.db' with your actual database file or connection string
    conn = sqlite3.connect('UberEats_data.db')
    df = pd.read_sql_query(query, conn)
    conn.close()
    return df

# 3. Define the 10 Predefined Business Questions & SQL
# Format: { "Display Question": "SQL Query" }
analysis_queries = {
    """1. What is the total revenue generated by each restaurant?
            Business Value: Identifies top-performing partners and helps in ranking restaurants by financial contribution."""
 
            : """SELECT restaurant_name, SUM(order_value) AS total_revenue FROM orders GROUP BY restaurant_name ORDER BY total_revenue DESC;""",
            
                
    """2. What is the most popular payment method used by customers?
            Business Value: Helps optimize payment partnerships and understand customer preferences for checkout."""
            
            :"""SELECT payment_method, COUNT(order_id) AS order_count FROM orders GROUP BY payment_method ORDER BY order_count DESC;""",
            
            
    """3. How many orders used a discount, and what was their average value?
            Business Value: Evaluates the effectiveness of promotional campaigns and whether discounted orders result in higher or lower spending."""
            
            
            :"""SELECT COUNT(order_id) AS discounted_orders, ROUND(AVG(order_value),2) AS avg_discounted_value FROM orders
            WHERE discount_used = 'Yes'; -- Assuming 'Yes'/'No' or specific codes""",
            
    """4. What is the daily trend of order volumes?
            Business Value: Pinpoints peak days of the week or specific dates with high demand to assist with staffing and resource allocation."""
            
            
            :"""SELECT order_date, COUNT(order_id) AS daily_order_count FROM orders GROUP BY order_date ORDER BY order_date LIMIT 30;""",
            
            
    """5. Which restaurants have an average order value (AOV) higher than $50?
            Business Value: Segments restaurants into "Premium" or "High-Value" categories for targeted marketing."""
            
            
            
            :"""SELECT restaurant_name,ROUND(AVG(order_value),2) AS aov  FROM orders  GROUP BY restaurant_name  HAVING aov > 50;"""
         
        
}

def main():
    st.title("📊 Business Analysis Q&A")
    st.info("Select a question from the list below to run the real-time SQL analysis.")
    
    

    # 4. Dropdown Selection
    selected_question = st.selectbox(
        "Which analysis would you like to view?",
        options=list(analysis_queries.keys())
    )

    # 5. Computation & Result Display
    if selected_question:
        st.subheader(f"Analysis: {selected_question}")
        
        query = analysis_queries[selected_question]
        
        try:
            # SQL-based computation
            with st.spinner('Running SQL Query...'):
                results_df = run_query(query)
            
            # Presentation in structured table
            st.dataframe(
                results_df, 
                use_container_width=True, 
                hide_index=True
            )
            
            # Optional: Add a CSV download button for the specific result
            csv = results_df.to_csv(index=False).encode('utf-8')
            st.download_button("📥 Download Results as CSV", csv, "analysis.csv", "text/csv")

        except Exception as e:
            st.error(f"Execution Error: {e}")

if __name__ == "__main__":
    main()
